#!/bin/sh
###########################################################################
# a2o Essential Puppet Modules                                            #
#-------------------------------------------------------------------------#
# Copyright (c) Bostjan Skufca                                            #
#-------------------------------------------------------------------------#
# This source file is subject to version 2.0 of the Apache License,       #
# that is bundled with this package in the file LICENSE, and is           #
# available through the world-wide-web at the following url:              #
# http://www.apache.org/licenses/LICENSE-2.0                              #
#-------------------------------------------------------------------------#
# Authors: Bostjan Skufca <my_name [at] a2o {dot} si>                     #
###########################################################################
#
# /etc/init.d/activemq
#
### BEGIN INIT INFO
# Provides:          activemq
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: ActiveMQ queueing service
# Description:       ActiveMQ queueing service
### END INIT INFO


# Init the startup script and reset status of this service
. /etc/rc.status
rc_reset


# Configuration of binaries and parameters
ACTIVEMQ_NAME="ActiveMQ"
ACTIVEMQ_BIN="/opt/activemq/bin/activemq"
ACTIVEMQ_PROC_CHKPROC="/usr/local/bin/java"
ACTIVEMQ_PROC="/opt/activemq/bin/run.jar"
ACTIVEMQ_PIDFILE="/var/activemq/activemq-`hostname`.pid"
ACTIVEMQ_CMD_START="/opt/activemq/bin/activemq start"
ACTIVEMQ_CMD_STOP="/opt/activemq/bin/activemq-admin stop"


# Test binary existence - THINK is this good? What if program in uninstalled but
# is left running in the background, effectively forgotten?
test -x $ACTIVEMQ_BIN || {
    echo "$ACTIVEMQ_BIN not installed";
    if [ "$1" = "stop" ] ; then
	exit 0
    else
	exit 5
    fi
}


# Execute command
case "$1" in
    start)
	if [ -e $ACTIVEMQ_PIDFILE ]; then
	    if checkproc $ACTIVEMQ_PROC_CHKPROC ; then
		echo "$ACTIVEMQ_NAME already started. Not starting."
		exit 0;
	    else
		echo "Removing stale PID file $ACTIVEMQ_PIDFILE";
		rm -f $ACTIVEMQ_PIDFILE;
	    fi
	fi
	echo -n "Starting $ACTIVEMQ_NAME "
	$ACTIVEMQ_CMD_START
	rc_status -v
	;;


    stop)
	echo -n "Stopping $ACTIVEMQ_NAME "
	$ACTIVEMQ_CMD_STOP
	rc_status -v
	rm -f $ACTIVEMQ_PIDFILE
	;;


    restart)
	$0 stop
	$0 start
	rc_status
	;;


    status)
	echo -n "Checking for service $ACTIVEMQ_NAME "

	RES=`ps auxfww | cat | grep "$ACTIVEMQ_PROC" | grep "$ACTIVEMQ_PROC_CHKPROC" | grep -c .`
	if [ "$RES" == "1" ]; then
	    (exit 0)
	elif [ "$RES" == "0" ]; then
	    (exit 3)
	else
	    (exit 4)
	fi

	rc_status -v
	;;


    *)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
	;;
esac


# Signal exit of a script
rc_exit
