#!/bin/bash
###########################################################################
# a2o Essential Puppet Modules                                            #
#-------------------------------------------------------------------------#
# Copyright (c) Bostjan Skufca                                            #
#-------------------------------------------------------------------------#
# This source file is subject to version 2.0 of the Apache License,       #
# that is bundled with this package in the file LICENSE, and is           #
# available through the world-wide-web at the following url:              #
# http://www.apache.org/licenses/LICENSE-2.0                              #
#-------------------------------------------------------------------------#
# Authors: Bostjan Skufca <my_name [at] a2o {dot} si>                     #
###########################################################################
#
# /etc/init.d/named
#
### BEGIN INIT INFO
# Provides:		named
# Required-Start:	$local_fs $syslog $network
# Required-Stop:	$local_fs $syslog $network
# Default-Start:	1 2 3 4 5
# Default-Stop:		0 6
# Short-Description:	Bind DNS server
# Long-Description:	Bind DNS server
### END INIT INFO
#
### BEGIN CHKCONFIG part
# chkconfig: 12345 55 25
# description: Bind DNS server
### END CHKCONFIG part


### Just run the rctool wrapper
/etc/rc.tool/wrapper.redhat named $@
