#!/bin/bash
###########################################################################
# a2o Essential Puppet Modules                                            #
#-------------------------------------------------------------------------#
# Copyright (c) Bostjan Skufca                                            #
#-------------------------------------------------------------------------#
# This source file is subject to version 2.0 of the Apache License,       #
# that is bundled with this package in the file LICENSE, and is           #
# available through the world-wide-web at the following url:              #
# http://www.apache.org/licenses/LICENSE-2.0                              #
#-------------------------------------------------------------------------#
# Authors: Bostjan Skufca <my_name [at] a2o {dot} si>                     #
###########################################################################

#
# WARNING: This file is controlled by configuration management system.
#

CHECK_IP="$1"
EXPECTED_HOSTNAME="$2"

RES=`dig -x $CHECK_IP +noall +answer | grep "$EXPECTED_HOSTNAME" | grep -c .`
if [ "$RES" == "0" ]; then
    echo "HOST rDNS CRITICAL: Reverse DNS entry for IP $CHECK_IP is not $EXPECTED_HOSTNAME"
    exit 2
elif [ "$RES" == "1" ]; then
    echo "HOST rDNS OK: $CHECK_IP ---> $EXPECTED_HOSTNAME"
    exit 0
else
    echo "HOST rDNS UNKNOWN: Multiple results for $CHECK_IP"
fi
