#!/bin/bash
###########################################################################
# a2o Essential Puppet Modules                                            #
#-------------------------------------------------------------------------#
# Copyright (c) Bostjan Skufca                                            #
#-------------------------------------------------------------------------#
# This source file is subject to version 2.0 of the Apache License,       #
# that is bundled with this package in the file LICENSE, and is           #
# available through the world-wide-web at the following url:              #
# http://www.apache.org/licenses/LICENSE-2.0                              #
#-------------------------------------------------------------------------#
# Authors: Bostjan Skufca <my_name [at] a2o {dot} si>                     #
###########################################################################

#
# WARNING: This file is controlled by configuration management system.
#

CHECK_HOSTNAME="$1"
EXPECTED_IP="$2"

RES=`dig $CHECK_HOSTNAME +noall +answer | grep $EXPECTED_IP | grep -c .`
if [ "$RES" == "0" ]; then
    echo "HOST DNS CRITICAL: DNS entry ($EXPECTED_IP) for host $CHECK_HOSTNAME not found"
    exit 2
elif [ "$RES" == "1" ]; then
    echo "HOST DNS OK: $CHECK_HOSTNAME ---> $EXPECTED_IP"
    exit 0
else
    echo "HOST DNS UNKNOWN: $CHECK_HOSTNAME ---> Multiple results"
    exit 3
fi
