#!/bin/bash
###########################################################################
# a2o Essential Puppet Modules                                            #
#-------------------------------------------------------------------------#
# Copyright (c) Bostjan Skufca                                            #
#-------------------------------------------------------------------------#
# This source file is subject to version 2.0 of the Apache License,       #
# that is bundled with this package in the file LICENSE, and is           #
# available through the world-wide-web at the following url:              #
# http://www.apache.org/licenses/LICENSE-2.0                              #
#-------------------------------------------------------------------------#
# Authors: Bostjan Skufca <my_name [at] a2o {dot} si>                     #
###########################################################################

#
# WARNING: This file is controlled by configuration management system.
#


### Settings
CHECK_SCRIPT="/opt/scripts/raid/check"


### Check if check script exists and is executable
if [ ! -f $CHECK_SCRIPT ]; then
    echo "ERROR: RAID check script not found: $CHECK_SCRIPT"
    exit 3
fi
if [ ! -x $CHECK_SCRIPT ]; then
    echo "ERROR: RAID check script not executable: $CHECK_SCRIPT"
    exit 3
fi


### Run it
RES=`$CHECK_SCRIPT`
if [ "$RES" == "OK" ]; then
    echo "RAID OK"
    exit 0
else
    echo "RAID $RES"
    exit 2
fi
