#!/bin/bash
###########################################################################
# a2o Essential Puppet Modules                                            #
#-------------------------------------------------------------------------#
# Copyright (c) 2012 Bostjan Skufca                                       #
#-------------------------------------------------------------------------#
# This source file is subject to version 2.0 of the Apache License,       #
# that is bundled with this package in the file LICENSE, and is           #
# available through the world-wide-web at the following url:              #
# http://www.apache.org/licenses/LICENSE-2.0                              #
#-------------------------------------------------------------------------#
# Authors: Bostjan Skufca <bostjan@a2o.si>                                #
###########################################################################



PFILE="$1"
if [[ ! -z `echo $PFILE | grep '\.\(tar\.gz\|tgz\)$'` ]]; then
    tar -xzf $PFILE
elif [[ ! -z `echo $PFILE | grep '\.tar\.bz2$'` ]]; then
    tar -xjf $PFILE
elif [[ ! -z `echo $PFILE | grep '\.tar$'` ]]; then
    tar -xf $PFILE
else
    echo "ERROR - unknown archive $PFILE"
    exit 1
fi
