#!/bin/bash
###########################################################################
# a2o Essential Puppet Modules                                            #
#-------------------------------------------------------------------------#
# Copyright (c) Bostjan Skufca                                            #
#-------------------------------------------------------------------------#
# This source file is subject to version 2.0 of the Apache License,       #
# that is bundled with this package in the file LICENSE, and is           #
# available through the world-wide-web at the following url:              #
# http://www.apache.org/licenses/LICENSE-2.0                              #
#-------------------------------------------------------------------------#
# Authors: Bostjan Skufca <my_name [at] a2o {dot} si>                     #
###########################################################################



PFILE="$1"
if [[ ! -z `echo $PFILE | grep '\.\(tar\.gz\|tgz\)$'` ]]; then
    tar -xzf $PFILE
elif [[ ! -z `echo $PFILE | grep '\.tar\.bz2$'` ]]; then
    tar -xjf $PFILE
elif [[ ! -z `echo $PFILE | grep '\.tar\.xz$'` ]]; then
    tar -xJf $PFILE
    # Another option, if your tar does not support -J yet
    #xz -dc $PFILE | tar -x
elif [[ ! -z `echo $PFILE | grep '\.bz2$'` ]]; then
    bunzip2 $PFILE
elif [[ ! -z `echo $PFILE | grep '\.tar$'` ]]; then
    tar -xf $PFILE
else
    echo "ERROR - unknown archive $PFILE"
    exit 1
fi
