#!/bin/sh
###########################################################################
# a2o Essential Puppet Modules                                            #
#-------------------------------------------------------------------------#
# Copyright (c) 2012 Bostjan Skufca                                       #
#-------------------------------------------------------------------------#
# This source file is subject to version 2.0 of the Apache License,       #
# that is bundled with this package in the file LICENSE, and is           #
# available through the world-wide-web at the following url:              #
# http://www.apache.org/licenses/LICENSE-2.0                              #
#-------------------------------------------------------------------------#
# Authors: Bostjan Skufca <my_name [at] a2o {dot} si>                     #
###########################################################################
#
# /etc/init.d/gearmand
#
### BEGIN INIT INFO
# Provides:          gearmand
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: Gearmand job server
# Description:       Gearmand job server
### END INIT INFO


# Init the startup script and reset status of this service
. /etc/rc.status
rc_reset


# Configuration of binary and parameters
GEARMAND_BIN="/usr/local/gearman/sbin/gearmand"
GEARMAND_PIDFILE="/var/gearman/run/gearmand.pid"
GEARMAND_PARAMS="--daemon --pid-file=$GEARMAND_PIDFILE --user=gearman --log-file=/var/log/gearmand.log"
GEARMAND_CMDLINE="$GEARMAND_BIN $GEARMAND_PARAMS"


# Test binary existence
test -x $GEARMAND_BIN || {
    echo "$GEARMAND_BIN not installed";
    if [ "$1" = "stop" ] ; then
	exit 0
    else
	exit 5
    fi
}


# Execute command
case "$1" in
    start)
	if [ -e $GEARMAND_PIDFILE ]; then
	    if checkproc $GEARMAND_BIN ; then
		echo "Gearmand already started. Not starting."
		exit 0;
	    else
		echo "Removing stale PID file $GEARMAND_PIDFILE";
		rm -f $GEARMAND_PIDFILE;
	    fi
	fi
	echo -n "Starting gearmand "
	startproc $GEARMAND_CMDLINE
	rc_status -v
	;;

    stop)
	echo -n "Stopping gearmand "
	killproc -TERM $GEARMAND_BIN
	rc_status -v
	;;

    try-restart|condrestart)
	$0 status
	if test $? = 0; then
	    $0 restart
	else
	    rc_reset
	fi
	rc_status
	;;

    restart)
	$0 stop
	$0 start
	rc_status
	;;

    status)
	echo -n "Checking for service gearmand "
	checkproc $GEARMAND_BIN
	rc_status -v
	;;

    *)
	echo "Usage: $0 {start|stop|try-restart|restart|status}"
	exit 1
	;;
esac


# Signal exit of a script
rc_exit
