dir-merge .rsync-filter
dir-merge .rsync-filter.site
- /aquota.user
+ /backup
- /backup/***
+ /dev/pts
- /dev/pts/***
+ /dev/.udev
- /dev/.udev/***
+ /home
- /home/***
+ /media/*
- /media/*/***
+ /mnt/*
- /mnt/*/***
+ /opt/***
+ /proc
- /proc/***
- /quota.user
- /ramdisk*/***
+ /root
- /root/.cpan/***
+ /root/test
- /root/test/***
+ /root/tmp
- /root/tmp/***
+ /root/***
+ /sys
- /sys/***
+ /tmp
+ /tmp/php
+ /tmp/php/*
- /tmp/php/*/***
- /tmp/***
+ /usr/home
- /usr/home/***
+ /usr/local/apache/domlogs
- /usr/local/apache/domlogs/***
+ /usr/local/apache/logs
- /usr/local/apache/logs/***
- /usr/local/cpanel/logs/*log
+ /usr/local/cpanel-rollback
- /usr/local/cpanel-rollback/***
+ /usr/obj
- /usr/obj/***
+ /usr/ports
- /usr/ports/***
- /usr/src/***
- /usr/swap*
- /usr/tmpDSK*
+ /var
- /var/***
